apiVersion: apps/v1
kind: Deployment
metadata:
  name: starter-argocd

spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: starter
    spec:
      containers:
        - name: starter
          image: 'gcr.io/sparksandbox/starter:v1.2'
          ports:
            - containerPort: 8080
  selector:
    matchLabels:
      app: starter
